### ISSUE TITLE
Learn to use a build system 

### ISSUE THREAD

**Issue by The-Epic** [MinemenFree/Practice#14]
This project needs to stop using system scops and learn to use maven  properly, you are distributing spigot jars which goes against the dmca and distributing a paid spigot fork. You are most likely open a dmca or copyright strike because of it, you already use maven you should know how to specify repos or add stuff to your local repo. System scope is just a bad idea and shouldnt be used.

**Comment by gabrielvicenteYT** [comment]
Most of the spigots are free & / open-source, and FoxSpigot is removed from MC-Market. Carbon has it's own knockback API that I'm currently using, so that's not a problem.

**Comment by gabrielvicenteYT** [comment]
Might remove Fox support entirely, though.
